# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "코드 사이닝 인증서 및 프로비저닝 프로파일 동기화"
  lane :sync_certificates do |options|
    match(type: options[:type] || "appstore")
  end

  desc "TestFlight 베타 배포"
  lane :beta do
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_PRIVATE_KEY"],
      is_key_content_base64: false,
      in_house: false
    )
    sync_certificates
    sh("cd .. && tuist generate --no-open")
    build_app(
      workspace: "ChaGok.xcworkspace",
      scheme: "App",
      export_method: "app-store",
      xcargs: "CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY='Apple Distribution' PROVISIONING_PROFILE_SPECIFIER='match AppStore com.yongms.ChaGokChaGok' DEVELOPMENT_TEAM=78QTJM9AD7 CODE_SIGNING_REQUIRED=YES"
    )
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end

  desc "App Store 배포"
  lane :release do
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_PRIVATE_KEY"],
      is_key_content_base64: false,
      in_house: false
    )
    sync_certificates
    sh("cd .. && tuist generate --no-open")
    build_app(
      workspace: "ChaGok.xcworkspace",
      scheme: "App",
      export_method: "app-store",
      xcargs: "CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY='Apple Distribution' PROVISIONING_PROFILE_SPECIFIER='match AppStore com.yongms.ChaGokChaGok' DEVELOPMENT_TEAM=78QTJM9AD7 CODE_SIGNING_REQUIRED=YES"
    )
    upload_to_app_store
  end
end
