# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "코드 사이닝 인증서 및 프로비저닝 프로파일 동기화"
  lane :sync_certificates do |options|
    match(type: options[:type] || "appstore")
  end

  def marketing_version
    config = File.read("../Tuist/ProjectDescriptionHelpers/Config.swift")
    match_data = config.match(/public let version = "(.+)"/)
    UI.user_error!("Config.swift에서 version을 찾을 수 없습니다.") unless match_data
    match_data[1]
  end

  desc "TestFlight 베타 배포"
  lane :beta do
    setup_api_key
    sync_certificates
    build_ipa(build_number: ENV["BUILD_NUMBER"])
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end

  desc "App Store 배포"
  lane :release do
    setup_api_key
    new_build_number = latest_testflight_build_number(version: marketing_version) + 1
    sync_certificates
    build_ipa(build_number: new_build_number.to_s)
    upload_to_app_store
  end

  private_lane :setup_api_key do
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_PRIVATE_KEY"],
      is_key_content_base64: false,
      in_house: false
    )
  end

  private_lane :build_ipa do |options|
    sh("cd .. && tuist generate --no-open")
    build_app(
      workspace: "ChaGok.xcworkspace",
      scheme: "App",
      clean: true,
      export_method: "app-store",
      xcargs: "CODE_SIGN_STYLE=Manual DEVELOPMENT_TEAM=78QTJM9AD7 CODE_SIGNING_REQUIRED=YES MARKETING_VERSION=#{marketing_version} CURRENT_PROJECT_VERSION=#{options[:build_number]}",
      export_options: {
        method: "app-store",
        teamID: "78QTJM9AD7",
        signingStyle: "manual",
        provisioningProfiles: {
          "com.yongms.ChaGokChaGok" => "match AppStore com.yongms.ChaGokChaGok"
        }
      }
    )
  end
end
