name: Beta

on:
  push:
    branches: ["dev"]

permissions:
  id-token: write
  contents: read

jobs:
  beta:
    runs-on: macos-26
    environment: FastLane
    env:
      TUIST_XDG_STATE_HOME: /tmp/tuist-state
    steps:
      - uses: actions/checkout@v6

      - uses: jdx/mise-action@v4

      - name: Install Ruby gems
        run: bundle install

      - name: Tuist auth login
        run: tuist auth login

      - name: Tuist setup cache
        run: tuist setup cache

      - name: Deploy to TestFlight
        env:
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.GIT_AUTHORIZATION }}
        run: bundle exec fastlane beta
